/**
 * MineTeck LLC | Urban Mining LLC
 * GTM Capital Raise Proposal — $500,000 USD
 * Generated by KlickSmartAI | Breakthrough Management Gold Fund I
 *
 * Usage: node generate_proposal.js
 * Prereq: npm install docx
 * Output: MineTeck_UrbanMining_Capital_Raise_Proposal.docx
 *
 * COMPLIANCE NOTE: This document is for accredited investors only under
 * Reg D 506(c). No returns guaranteed. All ESG claims evidence-based.
 */

const {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  Header, Footer, AlignmentType, HeadingLevel, BorderStyle, WidthType,
  ShadingType, VerticalAlign, PageNumber, PageBreak, LevelFormat
} = require('docx');
const fs = require('fs');

// ─── Brand Colors ─────────────────────────────────────────────────────────────
const NAVY      = "0A1628";   // Deep navy (Breakthrough brand)
const GOLD      = "B8860B";   // Dark gold
const GOLD_LITE = "D4AF37";   // Light gold accent
const SLATE     = "2C3E50";   // Section headers
const MID_GRAY  = "546E7A";   // Body secondary
const LIGHT_BG  = "F2F4F8";   // Table row alternates
const WHITE     = "FFFFFF";
const WARN_RED  = "8B0000";   // Compliance warnings

// ─── DXA Constants (US Letter 1" margins → 9360 DXA content width) ────────────
const PAGE_W    = 12240;
const PAGE_H    = 15840;
const MARGIN    = 1440;       // 1 inch
const CONTENT_W = PAGE_W - (MARGIN * 2); // 9360 DXA

// ─── Helper: Empty paragraph spacer ──────────────────────────────────────────
const sp = (before = 0, after = 120) => new Paragraph({
  children: [new TextRun("")],
  spacing: { before, after }
});

// ─── Helper: Horizontal rule ─────────────────────────────────────────────────
const hr = (color = GOLD) => new Paragraph({
  children: [new TextRun("")],
  border: {
    bottom: { style: BorderStyle.SINGLE, size: 6, color, space: 1 }
  },
  spacing: { before: 160, after: 160 }
});

// ─── Helper: Section heading (navy bar label) ─────────────────────────────────
const sectionLabel = (text) => new Paragraph({
  children: [new TextRun({
    text: text.toUpperCase(),
    bold: true,
    color: WHITE,
    size: 20,
    font: "Arial"
  })],
  shading: { fill: NAVY, type: ShadingType.CLEAR },
  spacing: { before: 240, after: 160 },
  indent: { left: 120, right: 120 }
});

// ─── Helper: Body paragraph ───────────────────────────────────────────────────
const body = (text, opts = {}) => new Paragraph({
  children: [new TextRun({
    text,
    size: 22,
    font: "Arial",
    color: opts.color || SLATE,
    bold: opts.bold || false,
    italics: opts.italics || false
  })],
  spacing: { before: 60, after: 120 },
  alignment: opts.align || AlignmentType.LEFT
});

// ─── Helper: Key-value inline ─────────────────────────────────────────────────
const kv = (label, value, labelColor = GOLD, valueColor = SLATE) => new Paragraph({
  children: [
    new TextRun({ text: label + ": ", bold: true, size: 22, color: labelColor, font: "Arial" }),
    new TextRun({ text: value, size: 22, color: valueColor, font: "Arial" })
  ],
  spacing: { before: 60, after: 80 }
});

// ─── Helper: Build a standard table row ──────────────────────────────────────
const borderDef = { style: BorderStyle.SINGLE, size: 1, color: "DDDDDD" };
const cellBorders = {
  top: borderDef, bottom: borderDef, left: borderDef, right: borderDef
};

const tRow = (cells, isHeader = false) => new TableRow({
  tableHeader: isHeader,
  children: cells.map(({ text, width, align, shade, colspan }) =>
    new TableCell({
      columnSpan: colspan || 1,
      borders: cellBorders,
      width: { size: width || Math.floor(CONTENT_W / cells.length), type: WidthType.DXA },
      shading: { fill: shade || (isHeader ? NAVY : WHITE), type: ShadingType.CLEAR },
      margins: { top: 80, bottom: 80, left: 140, right: 140 },
      verticalAlign: VerticalAlign.CENTER,
      children: [new Paragraph({
        alignment: align || AlignmentType.LEFT,
        children: [new TextRun({
          text: String(text),
          size: 20,
          font: "Arial",
          bold: isHeader,
          color: isHeader ? WHITE : SLATE
        })]
      })]
    })
  )
});

// ─── Helper: Build a full table ───────────────────────────────────────────────
const makeTable = (headers, rows, colWidths) => {
  const totalWidth = colWidths.reduce((a, b) => a + b, 0);
  return new Table({
    width: { size: CONTENT_W, type: WidthType.DXA },
    columnWidths: colWidths,
    rows: [
      tRow(
        headers.map((h, i) => ({ text: h, width: colWidths[i] })),
        true
      ),
      ...rows.map((row, ri) =>
        tRow(
          row.map((cell, i) => ({
            text: cell,
            width: colWidths[i],
            shade: ri % 2 === 0 ? WHITE : LIGHT_BG
          }))
        )
      )
    ]
  });
};

// ─── Numbering Config ─────────────────────────────────────────────────────────
const numberingConfig = [
  {
    reference: "bullets",
    levels: [{
      level: 0,
      format: LevelFormat.BULLET,
      text: "•",
      alignment: AlignmentType.LEFT,
      style: { paragraph: { indent: { left: 720, hanging: 360 } } }
    }]
  },
  {
    reference: "check",
    levels: [{
      level: 0,
      format: LevelFormat.BULLET,
      text: "✓",
      alignment: AlignmentType.LEFT,
      style: { paragraph: { indent: { left: 720, hanging: 360 } } }
    }]
  }
];

const bullet = (text, bold = false, color = SLATE) => new Paragraph({
  numbering: { reference: "bullets", level: 0 },
  children: [new TextRun({ text, size: 22, font: "Arial", bold, color })],
  spacing: { before: 40, after: 60 }
});

const check = (text) => new Paragraph({
  numbering: { reference: "check", level: 0 },
  children: [new TextRun({ text, size: 22, font: "Arial", color: SLATE })],
  spacing: { before: 40, after: 60 }
});

// ─── Header / Footer ──────────────────────────────────────────────────────────
const docHeader = new Header({
  children: [
    new Paragraph({
      children: [
        new TextRun({ text: "CONFIDENTIAL — ACCREDITED INVESTORS ONLY  |  REG D 506(c)", size: 16, font: "Arial", color: MID_GRAY }),
        new TextRun({ text: "  |  ", size: 16, color: MID_GRAY }),
        new TextRun({ text: "MineTeck LLC | Urban Mining LLC", size: 16, bold: true, font: "Arial", color: NAVY })
      ],
      border: { bottom: { style: BorderStyle.SINGLE, size: 4, color: GOLD, space: 1 } },
      spacing: { after: 0 }
    })
  ]
});

const docFooter = new Footer({
  children: [
    new Paragraph({
      children: [
        new TextRun({ text: "This document contains forward-looking statements and is for informational purposes only. Past performance does not guarantee future results.  |  Page ", size: 16, font: "Arial", color: MID_GRAY }),
        new TextRun({ children: [PageNumber.CURRENT], size: 16, font: "Arial", color: MID_GRAY })
      ],
      border: { top: { style: BorderStyle.SINGLE, size: 4, color: GOLD, space: 1 } },
      spacing: { before: 0 }
    })
  ]
});

// ═════════════════════════════════════════════════════════════════════════════
// SECTION BUILDERS
// ═════════════════════════════════════════════════════════════════════════════

function buildCoverPage() {
  return [
    sp(1440),
    new Paragraph({
      children: [new TextRun({
        text: "BREAKTHROUGH MANAGEMENT GOLD FUND I",
        size: 20, bold: true, color: GOLD_LITE, font: "Arial",
        allCaps: true
      })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 60 }
    }),
    sp(80),
    new Paragraph({
      children: [new TextRun({
        text: "CAPITAL RAISE PROPOSAL",
        size: 44, bold: true, color: WHITE, font: "Arial"
      })],
      shading: { fill: NAVY, type: ShadingType.CLEAR },
      alignment: AlignmentType.CENTER,
      spacing: { before: 120, after: 0 }
    }),
    new Paragraph({
      children: [new TextRun({
        text: "MineTeck LLC  |  Urban Mining LLC",
        size: 32, bold: false, color: WHITE, font: "Arial"
      })],
      shading: { fill: NAVY, type: ShadingType.CLEAR },
      alignment: AlignmentType.CENTER,
      spacing: { before: 0, after: 240 }
    }),
    sp(160),
    new Paragraph({
      children: [new TextRun({
        text: "GTM Seed Round  |  $500,000 USD",
        size: 40, bold: true, color: GOLD_LITE, font: "Arial"
      })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 80, after: 80 }
    }),
    hr(GOLD),
    sp(160),
    makeTable(
      [],
      [
        ["Offering Type",     "Reg D 506(c) — Accredited Investors Only"],
        ["Jurisdiction",      "United States | Colorado"],
        ["Capital Target",    "$500,000 USD — Seed / Pilot Round"],
        ["Minimum Check",     "$25,000 USD"],
        ["Use of Proceeds",   "Operations, Technology & GTM Infrastructure"],
        ["Timeline",          "90-Day Close Target"],
        ["Securities Counsel","Fulsher Law Group PC"],
        ["Fund Manager",      "Breakthrough Management LLC"],
        ["Prepared By",       "KlickSmartAI.com | Capital Formation Systems"],
        ["Date",              "June 2026"]
      ],
      [3120, 6240]
    ),
    sp(200),
    new Paragraph({
      children: [new TextRun({
        text: "CONFIDENTIAL INFORMATION MEMORANDUM",
        size: 18, bold: true, color: WARN_RED, font: "Arial", allCaps: true
      })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 60 }
    }),
    new Paragraph({
      children: [new TextRun({
        text: "This document is intended solely for accredited investors as defined under Rule 501 of Regulation D. No offer or solicitation of securities is made to non-accredited investors. All investment involves risk. See Risk Factors section.",
        size: 18, color: MID_GRAY, font: "Arial", italics: true
      })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 120 }
    }),
    new Paragraph({ children: [new PageBreak()] })
  ];
}

function buildDisclaimerPage() {
  return [
    sectionLabel("Important Legal Notices & Compliance Disclosures"),
    sp(120),
    body("PRIVATE PLACEMENT — NOT A PUBLIC OFFERING", { bold: true, color: WARN_RED }),
    body("This Capital Raise Proposal (the 'Memorandum') is being furnished on a confidential basis solely to accredited investors (as defined in Rule 501(a) of Regulation D under the Securities Act of 1933, as amended) in connection with a potential private placement of securities by MineTeck LLC and Urban Mining LLC ('the Companies')."),
    sp(80),
    body("This offering has not been registered under the Securities Act of 1933 or the securities laws of any state. The securities offered hereby are being offered in reliance upon the exemption from registration provided by Rule 506(c) of Regulation D."),
    sp(80),
    body("NO GUARANTEE OF RETURNS", { bold: true, color: WARN_RED }),
    body("Nothing in this Memorandum constitutes a guarantee, promise, or representation of any specific return on investment. All projected revenues, cash flows, and financial outcomes are forward-looking statements subject to material risks and uncertainties. Past performance of any asset, project, or management team described herein does not guarantee future results."),
    sp(80),
    body("FORWARD-LOOKING STATEMENTS", { bold: true, color: SLATE }),
    body("This Memorandum contains forward-looking statements including projections of revenue, processing capacity, market size, and operational timelines. Such statements are based on management's current beliefs and assumptions and are subject to risks that could cause actual outcomes to differ materially. The Companies undertake no obligation to update forward-looking statements."),
    sp(80),
    body("ESG / ENVIRONMENTAL CLAIMS", { bold: true, color: SLATE }),
    body("Environmental, social, and governance (ESG) statements in this Memorandum are based on third-party testing and technical reports where cited. Unverified claims are labeled as management projections. The Companies do not guarantee compliance with any ESG certification standard."),
    sp(80),
    body("LEGAL COUNSEL REQUIRED", { bold: true, color: SLATE }),
    body("Prospective investors should consult their own legal, tax, and financial advisors before making any investment decision. KlickSmartAI provides capital formation marketing systems only and does not provide legal, financial, or securities advice. Securities counsel: Fulsher Law Group PC."),
    sp(80),
    body("CONFIDENTIALITY", { bold: true, color: SLATE }),
    body("By receiving this Memorandum, you agree to hold its contents in strict confidence and not to copy, reproduce, or distribute it without prior written consent from Breakthrough Management LLC."),
    new Paragraph({ children: [new PageBreak()] })
  ];
}

function buildExecutiveSummary() {
  return [
    sectionLabel("Executive Summary"),
    sp(100),
    new Paragraph({
      children: [new TextRun({
        text: "A Rare Convergence: Clean Mining Technology Meets ESG Impact Capital",
        size: 28, bold: true, color: NAVY, font: "Arial"
      })],
      spacing: { before: 80, after: 160 }
    }),
    body("Breakthrough Management Gold Fund I is launching a targeted $500,000 seed round to fund the initial operational phase of two portfolio companies — MineTeck LLC and Urban Mining LLC — that together represent a vertically integrated, environmentally responsible precious metals recovery platform."),
    sp(80),
    body("MineTeck LLC operates Colorado's first newly permitted toll milling facility in over 20 years — the Gladstone Toll Mill (GTM) — alongside the Gladstone Mines underground hard rock operation and Russell Gulch gold property. Urban Mining LLC has secured a commercial-grade PCB (printed circuit board) e-waste processing operation with a binding offtake term sheet from Ocean Partners, one of the world's leading precious metals trading and recycling firms."),
    sp(80),
    body("This $500,000 seed round funds the critical first 90 days: site development, water circuit installation, initial processing equipment, and the go-to-market infrastructure required to attract the full $25M Gold Fund I capital raise."),
    sp(120),
    sectionLabel("The Investment Thesis at a Glance"),
    sp(80),
    makeTable(
      ["Dimension", "MineTeck LLC", "Urban Mining LLC"],
      [
        ["Core Asset",      "Gladstone Toll Mill + Mines",     "PCB E-Waste Processing Plant"],
        ["Revenue Model",   "Toll milling fees + metal sales", "Precious metals from PCB recovery"],
        ["Capacity",        "15–50 TPH (scalable MRU)",        "~1 tonne/day Phase 1"],
        ["Key Partner",     "Colorado regulators / operators", "Ocean Partners (offtake term sheet)"],
        ["ESG Profile",     "Zero liquid discharge / MRU",     "Urban mining / circular economy"],
        ["Raise (Total)",   "$4M Gladstone component",         "~$5M ESG/impact round"],
        ["Seed Ask",        "$200,000",                        "$300,000"],
        ["Seed Total",      "$500,000 combined",               ""]
      ],
      [3000, 3180, 3180]
    ),
    sp(160),
    kv("Combined Seed Capital Required", "$500,000 USD"),
    kv("Minimum Investment", "$25,000 per accredited investor"),
    kv("Structure", "Reg D 506(c) Private Placement"),
    kv("Securities Counsel", "Fulsher Law Group PC (Colorado)"),
    kv("Target Close", "90 days from first close"),
    new Paragraph({ children: [new PageBreak()] })
  ];
}

function buildMarketOpportunity() {
  return [
    sectionLabel("The Market Opportunity"),
    sp(100),
    new Paragraph({
      children: [new TextRun({
        text: "Two Converging Megatrends: Gold Infrastructure Gap + E-Waste Crisis",
        size: 26, bold: true, color: NAVY, font: "Arial"
      })],
      spacing: { before: 80, after: 160 }
    }),
    body("Colorado's Front Range and historic mining districts hold hundreds of millions of dollars in stranded gold and precious metal assets — stalled not by lack of resource but by lack of processing infrastructure. At the same time, global e-waste output has reached 53 million metric tonnes annually, with less than 20% formally recycled and up to 7% of the world's gold supply trapped in discarded electronics."),
    sp(80),

    sectionLabel("Opportunity 1: Colorado Toll Milling — A 20-Year Infrastructure Gap"),
    body("The Gladstone Toll Mill is the first permitted toll milling operation in Colorado in over 20 years. Small and mid-size mine operators across the state have been shipping ore out of state for processing — at significant cost and delay. MineTeck's permitted in-state facility creates immediate, high-margin revenue from day one of operations."),
    sp(60),
    makeTable(
      ["Market Factor", "Detail"],
      [
        ["Colorado mining districts",       "100+ active small/mid operations seeking local processing"],
        ["Average toll milling margin",     "40–60% gross margins on processing fees"],
        ["Processing capacity (Phase 1)",   "15 TPH, scalable to 50 TPH with MRU upgrade"],
        ["Projected Year 1 revenue (GTM)",  "$17M (based on management projections)"],
        ["Permitting barrier to entry",     "High — 20+ year gap proves regulatory moat"]
      ],
      [3500, 5860]
    ),
    sp(160),

    sectionLabel("Opportunity 2: E-Waste Gold Recovery — Urban Mining"),
    body("Urban Mining LLC's PCB processing operation recovers gold, silver, platinum, and palladium from printed circuit boards using proprietary non-cyanide extraction technology (IMG Gold Recovery system). With 86% reported recovery rates and a binding offtake term sheet from Ocean Partners, Urban Mining enters Phase 1 with revenue visibility from day one."),
    sp(60),
    makeTable(
      ["Market Factor", "Detail"],
      [
        ["Global e-waste generated annually",     "53 million metric tonnes (2023)"],
        ["Gold trapped in e-waste",               "~7% of global annual gold supply"],
        ["Recovery rate (IMG technology)",        "86% (as reported by technology provider)"],
        ["Offtake partner",                       "Ocean Partners — binding term sheet secured"],
        ["Feedstock supply partner",              "EWC Group — supply relationship in place"],
        ["Phase 1 processing target",             "~1 tonne/day PCB feedstock"]
      ],
      [3500, 5860]
    ),
    new Paragraph({ children: [new PageBreak()] })
  ];
}

function buildMineTeckSection() {
  return [
    sectionLabel("MineTeck LLC — Company Overview & Technology"),
    sp(100),
    new Paragraph({
      children: [new TextRun({
        text: "Zero-Waste Mining Technology with a Regulatory Moat",
        size: 26, bold: true, color: NAVY, font: "Arial"
      })],
      spacing: { before: 80, after: 160 }
    }),
    body("MineTeck LLC is a Colorado-based clean mining technology company operating the Gladstone Toll Mill — the only newly permitted toll milling facility in Colorado in more than 20 years. MineTeck's Mobile Research Unit (MRU) technology enables scalable, self-contained precious metal recovery with zero liquid discharge and independently verified zero toxicity."),
    sp(80),

    body("Core Assets", { bold: true, color: NAVY }),
    bullet("Gladstone Toll Mill (GTM): First permitted in-state toll milling operation in CO in 20+ years. Projected $17M annual revenue at full capacity. Initial investment: $4M."),
    bullet("Russell Gulch Gold Property: 3 grams per tonne gold grade. $1.25M initial investment, $8M projected project value."),
    bullet("Gladstone Mines Underground: Hard rock operation. $500,000 initial funding phase (covered by this seed round, $200K allocation)."),
    bullet("B Group Property: Long-term strategic asset. $4.5M investment, $85M 10-year projected value."),
    sp(80),

    body("The MRU Technology Advantage", { bold: true, color: NAVY }),
    body("The Mobile Research Unit (MRU) is MineTeck's proprietary modular processing system:"),
    bullet("Current capacity: 15 tonnes per hour (TPH)"),
    bullet("Upgrade pathway: 50 TPH — scales without additional permitting"),
    bullet("Zero-liquid discharge: All process water recycled in closed loop"),
    bullet("TCLP, SPLP, and ABA tests confirm zero toxicity for 1,000+ year horizon (third-party verified)"),
    bullet("Circular economy design: All tailings repurposed; no toxic waste streams"),
    sp(80),

    body("Gladstone Mines — Seed Round Allocation ($200,000)", { bold: true, color: NAVY }),
    makeTable(
      ["Use of Funds", "Amount"],
      [
        ["Site Development & Access Roads",    "$75,000"],
        ["Water Circuit Installation",         "$80,000"],
        ["Processing Equipment — Phase 1",     "$30,000"],
        ["Environmental Compliance & Permits", "$10,000"],
        ["Contingency (5%)",                   "$5,000"],
        ["Total",                              "$200,000"]
      ],
      [6240, 3120]
    ),
    new Paragraph({ children: [new PageBreak()] })
  ];
}

function buildUrbanMiningSection() {
  return [
    sectionLabel("Urban Mining LLC — Company Overview"),
    sp(100),
    new Paragraph({
      children: [new TextRun({
        text: "From E-Waste to Gold: A Closed-Loop Precious Metals Recovery Model",
        size: 26, bold: true, color: NAVY, font: "Arial"
      })],
      spacing: { before: 80, after: 160 }
    }),
    body("Urban Mining LLC processes end-of-life printed circuit boards (PCBs) using advanced non-cyanide precious metal extraction technology to recover gold, silver, platinum, and palladium. The company has secured commercial-grade supply through EWC Group and a binding offtake term sheet from Ocean Partners."),
    sp(80),

    body("Business Model Summary", { bold: true, color: NAVY }),
    bullet("Acquire PCB feedstock from certified e-waste recyclers (primary: EWC Group)"),
    bullet("Process using IMG Gold Recovery technology at 86% reported recovery rate"),
    bullet("Sell recovered precious metals under Ocean Partners offtake term sheet"),
    bullet("Expand to full-scale Plant at commercial viability (Phase 2)"),
    sp(80),

    body("Key Commercial Relationships", { bold: true, color: NAVY }),
    makeTable(
      ["Partner", "Role", "Status"],
      [
        ["Ocean Partners",    "Precious metals offtake buyer",              "Binding term sheet secured"],
        ["EWC Group",         "PCB feedstock supply",                       "Supply relationship in place"],
        ["IMG Gold Recovery", "Processing technology provider",              "Technology integration confirmed"]
      ],
      [2500, 4000, 2860]
    ),
    sp(80),

    body("Phase 1 Operations (Seed Round Funded)", { bold: true, color: NAVY }),
    bullet("Establish commercial-grade PCB processing circuit"),
    bullet("Validate recovery rates and yield data for investor due diligence"),
    bullet("Generate first commercial revenue batch via Ocean Partners"),
    bullet("Build operational track record to underpin Phase 2 / $5M ESG round"),
    sp(80),

    body("Urban Mining LLC — Seed Round Allocation ($300,000)", { bold: true, color: NAVY }),
    makeTable(
      ["Use of Funds", "Amount"],
      [
        ["Commercial Circuit Build-Out",            "$175,000"],
        ["Feedstock Acquisition (first batch)",     "$60,000"],
        ["Processing Equipment (additional)",       "$35,000"],
        ["Legal & Compliance",                      "$15,000"],
        ["Working Capital & Contingency",           "$15,000"],
        ["Total",                                   "$300,000"]
      ],
      [6240, 3120]
    ),
    new Paragraph({ children: [new PageBreak()] })
  ];
}

function buildGTMStrategy() {
  return [
    sectionLabel("GTM Capital Raise Strategy — KlickSmartAI Framework"),
    sp(100),
    new Paragraph({
      children: [new TextRun({
        text: "Outcome-Based Investor Acquisition: Warm First, Compliant Always",
        size: 26, bold: true, color: NAVY, font: "Arial"
      })],
      spacing: { before: 80, after: 160 }
    }),
    body("The GTM (Go-To-Market) capital raise strategy is designed by KlickSmartAI as a compliance-first, systems-driven investor acquisition engine. All activities operate within Reg D 506(c) parameters with accreditation verification before any substantive investment discussion."),
    sp(80),

    body("Phase 1 — Warm Market Activation (Days 1–45)", { bold: true, color: NAVY }),
    body("Deploy the FORD+Dream warm mapping framework: Friends, Occupation, Recreation, Dream. All Phase 1 outreach targets individuals with a pre-existing relationship to the principals — Andrew Ferguson, Gilbert Jones, Brett Stokes, and Dennis Eng."),
    bullet("Target: 50–100 warm contacts per principal"),
    bullet("Channels: Personal phone, email, LinkedIn (1st degree only)"),
    bullet("Goal: $250,000 of the $500,000 seed from warm market"),
    bullet("Compliance gate: Accreditation pre-screening before any deck is shared"),
    sp(60),

    body("Phase 2 — Qualified Cold Outreach (Days 30–90)", { bold: true, color: NAVY }),
    body("Deploy multi-channel cold outreach via Smartlead + Apollo.io targeting accredited investor segments using general solicitation permitted under 506(c)."),
    bullet("Target segments: CSM alumni, Denver Gold Forum contacts, SME members, Family Offices, HNWI (FINTRX/Family Office Access lists)"),
    bullet("Expected reply rate: 1–3% (realistic for HNWI audiences)"),
    bullet("Volume: ~2,000 contacts across 7 priority tiers"),
    bullet("Platform: Avestor for investor portal, accreditation, and ACH"),
    sp(80),

    body("Investor Funnel Architecture", { bold: true, color: NAVY }),
    makeTable(
      ["Stage", "Action", "Platform", "Compliance Gate"],
      [
        ["1. Awareness",    "LinkedIn / video / email outreach",  "Smartlead + Apollo",  "None (506(c) allows general solicitation)"],
        ["2. Interest",     "Book intro call",                     "HubSpot CRM",         "Accreditation signal check"],
        ["3. Qualification","Accreditation verification",          "Avestor portal",      "KYC/AML + accreditation docs required"],
        ["4. Education",    "NDA + Data Room access",              "Avestor Data Room",   "NDA signed, accreditation confirmed"],
        ["5. Conversion",   "Term sheet → subscription agreement", "Avestor + DocuSign",  "Fulsher Law Group review required"],
        ["6. Close",        "Capital receipt + investor onboard",  "Avestor ACH",         "Post-close reporting begins"]
      ],
      [1560, 2200, 1800, 3800]
    ),
    sp(80),

    body("Target Investor Profiles", { bold: true, color: NAVY }),
    makeTable(
      ["Profile", "Check Size", "Primary Trigger", "Channel"],
      [
        ["HNWI — Warm Network",        "$25K–$100K",   "Trust / relationship",       "Phone / personal email"],
        ["CSM / SME Alumni",           "$50K–$250K",   "Technical credibility",       "LinkedIn / email"],
        ["Denver Gold Forum Network",  "$50K–$500K",   "Sector expertise",            "In-person / LinkedIn"],
        ["Family Offices",             "$100K–$1M",    "ESG + projected returns",     "FINTRX / curated intro"],
        ["Impact / ESG Funds",         "$250K–$2M",    "Environmental mandate",       "Targeted campaign"],
        ["Resource Sector Funds",      "$500K–$5M",    "Sector allocation mandate",   "Direct outreach + deck"]
      ],
      [2400, 1560, 2400, 3000]
    ),
    new Paragraph({ children: [new PageBreak()] })
  ];
}

function buildUseOfFunds() {
  return [
    sectionLabel("Use of Funds — $500,000 Seed Round"),
    sp(100),
    new Paragraph({
      children: [new TextRun({
        text: "Capital Allocation Summary",
        size: 26, bold: true, color: NAVY, font: "Arial"
      })],
      spacing: { before: 80, after: 160 }
    }),
    makeTable(
      ["Allocation", "Entity", "Amount", "% of Total", "Purpose"],
      [
        ["MineTeck — Gladstone Mines",  "MineTeck LLC",     "$200,000", "40%", "Site development, water circuit, equipment"],
        ["Urban Mining — Phase 1",      "Urban Mining LLC", "$300,000", "60%", "Commercial circuit, feedstock, compliance"],
        ["  — Commercial Circuit",      "Urban Mining LLC", "$175,000", "35%", "PCB processing build-out"],
        ["  — Feedstock Acquisition",   "Urban Mining LLC", "$60,000",  "12%", "First commercial PCB batch"],
        ["  — Equipment",               "Urban Mining LLC", "$35,000",  "7%",  "Processing equipment additions"],
        ["  — Legal & Compliance",      "Urban Mining LLC", "$15,000",  "3%",  "Securities & operating counsel"],
        ["  — Working Capital",         "Urban Mining LLC", "$15,000",  "3%",  "Operating contingency"],
        ["TOTAL",                       "",                 "$500,000", "100%", ""]
      ],
      [2400, 1800, 1200, 1000, 2960]
    ),
    sp(120),

    body("GTM Infrastructure (Funded Separately by KlickSmartAI Engagement)", { bold: true, color: MID_GRAY, italics: true }),
    body("Note: The investor acquisition infrastructure (Avestor platform, HubSpot CRM, Smartlead email system, Apollo.io enrichment, RIOS relationship intelligence system) is funded separately under the KlickSmartAI engagement — not from seed investor capital. This preserves maximum investor capital for direct operational deployment.", { color: MID_GRAY, italics: true }),
    sp(80),

    body("90-Day Deployment Schedule", { bold: true, color: NAVY }),
    makeTable(
      ["Days", "Milestone", "Capital Deployed"],
      [
        ["1–15",  "Seed close + entity setup + securities filing (Fulsher Law)", "$0 operational"],
        ["16–30", "MineTeck site access, survey, water circuit begins",           "$50,000"],
        ["31–60", "Urban Mining circuit installation + feedstock acquisition",    "$200,000"],
        ["61–75", "MineTeck equipment commissioning + Urban Mining pilot run",    "$150,000"],
        ["76–90", "First commercial production + investor reporting",             "$100,000"],
        ["Day 90","Full $500K deployed, Phase 2 raise launched",                 "$500,000 total"]
      ],
      [1200, 5400, 2760]
    ),
    new Paragraph({ children: [new PageBreak()] })
  ];
}

function buildFinancials() {
  return [
    sectionLabel("Financial Projections — Management Estimates"),
    sp(60),
    body("IMPORTANT: The following projections are management estimates based on current operator data, engineering reports, and market pricing. They are forward-looking statements subject to material risks and should not be relied upon as guarantees of performance.", { color: WARN_RED, italics: true }),
    sp(80),

    body("MineTeck Portfolio — Revenue Projections", { bold: true, color: NAVY }),
    makeTable(
      ["Asset", "Investment", "Projected Annual Revenue", "Notes"],
      [
        ["Gladstone Toll Mill",          "$4,000,000",   "$17,000,000",  "Toll milling fees + metal sales"],
        ["Russell Gulch",                "$1,250,000",   "$8,000,000",   "3 gpt gold grade; $8M project"],
        ["Crown Mining Property",        "$3,600,000",   "Part of $120M","Long-term strategic asset"],
        ["B Group Property",             "$4,500,000",   "$85,000,000",  "10-year projected value"],
        ["Gladstone Mines (Seed)",       "$500,000",     "TBD (Phase 1)","First 90-day operational phase"],
        ["1027 Toll Plant (add-on)",     "$750,000",     "TBD",          "Additional processing capacity"]
      ],
      [2600, 1800, 2400, 2560]
    ),
    sp(80),

    body("Urban Mining LLC — Phase 1 Financial Model (Management Estimate)", { bold: true, color: NAVY }),
    makeTable(
      ["Metric", "Value", "Basis"],
      [
        ["Phase 1 processing rate",       "~1 tonne/day PCB",      "Initial commercial circuit capacity"],
        ["Gold recovery rate",            "86% (reported)",         "IMG Gold Recovery technology spec"],
        ["Typical PCB gold content",      "200–400g per tonne",     "Industry standard for high-grade PCB"],
        ["Revenue per tonne (est.)",      "~$8,000–$16,000",        "Based on spot gold ~$3,200/oz (June 2026)"],
        ["Monthly revenue potential",     "$240K–$480K",            "At 30 days processing per month"],
        ["Ocean Partners offtake",        "Binding term sheet",     "Committed off-take buyer in place"]
      ],
      [3000, 2880, 3480]
    ),
    sp(80),

    body("Gold Fund I — Total Raise Summary", { bold: true, color: NAVY }),
    makeTable(
      ["Fund Component", "Capital Target", "Status"],
      [
        ["Gladstone Toll Mill",           "$4,000,000",   "Priority close — permitted & operational ready"],
        ["Russell Gulch",                 "$1,250,000",   "Active development"],
        ["Crown Mining",                  "$3,600,000",   "Acquisition target"],
        ["B Group",                       "$4,500,000",   "Long-term strategic"],
        ["Urban Mining LLC",              "~$5,000,000",  "ESG/impact round — Ocean Partners secured"],
        ["RAD Exploration Systems",       "$500,000",     "Strategic technology investment"],
        ["1027 Toll Plant",               "$750,000",     "Add-on processing asset"],
        ["TOTAL FUND I TARGET",           "$25,000,000",  ""],
        ["Seed Round (this offering)",    "$500,000",     "90-day close target"]
      ],
      [3500, 2300, 3560]
    ),
    new Paragraph({ children: [new PageBreak()] })
  ];
}

function buildRiskFactors() {
  return [
    sectionLabel("Risk Factors"),
    sp(80),
    body("Prospective investors must carefully consider the following risk factors before making any investment decision. This list is not exhaustive. Investors are urged to consult with their own legal, tax, and financial advisors.", { color: WARN_RED, italics: true }),
    sp(80),

    body("Operational Risks", { bold: true, color: NAVY }),
    bullet("Mining and processing operations are subject to equipment failure, geological uncertainty, and supply chain disruption."),
    bullet("PCB feedstock availability may vary; EWC Group supply relationship is not guaranteed at projected volumes."),
    bullet("The 86% gold recovery rate cited is based on IMG technology specifications; actual field performance may differ."),
    bullet("The Gladstone Toll Mill processing capacity target (15–50 TPH) is subject to engineering validation."),
    sp(60),

    body("Market & Commodity Risks", { bold: true, color: NAVY }),
    bullet("Gold, silver, platinum, and palladium prices are volatile. A sustained decline in precious metals prices would materially impact revenue projections."),
    bullet("Toll milling fee rates are competitive and may be subject to downward pressure from competing facilities."),
    sp(60),

    body("Regulatory & Permitting Risks", { bold: true, color: NAVY }),
    bullet("All operations are subject to Colorado state and federal environmental regulations. Additional permits may be required and may be delayed or denied."),
    bullet("E-waste processing regulations are evolving and may impose additional compliance costs."),
    sp(60),

    body("Capital & Financing Risks", { bold: true, color: NAVY }),
    bullet("The $500,000 seed round may not be sufficient to achieve Phase 1 milestones if costs exceed projections."),
    bullet("There is no guarantee that the full Gold Fund I ($25M) or Urban Mining (~$5M) rounds will be raised."),
    bullet("Investors may not be able to liquidate their investment — no secondary market exists for these securities."),
    sp(60),

    body("Management & Execution Risks", { bold: true, color: NAVY }),
    bullet("The Companies are dependent on key individuals including Andrew Ferguson, Gilbert Jones, and Brett Stokes."),
    bullet("The RIOS capital formation system and investor outreach infrastructure are early-stage; results are not guaranteed."),
    sp(60),

    body("ESG / Environmental Risks", { bold: true, color: NAVY }),
    bullet("Zero-toxicity claims are based on TCLP/SPLP/ABA test results to date; ongoing compliance requires continued monitoring."),
    bullet("Urban Mining's environmental claims are subject to third-party audit and may change as operations scale."),
    new Paragraph({ children: [new PageBreak()] })
  ];
}

function buildTeamPage() {
  return [
    sectionLabel("Management Team & Advisors"),
    sp(100),
    makeTable(
      ["Name", "Role", "Background"],
      [
        ["Andrew Ferguson",      "Founder & CEO, Breakthrough Management",  "Fund principal; Colorado mining industry veteran; Gold Fund I architect"],
        ["Gilbert Jones",        "EVP & Co-Founder",                        "Operations lead; feedstock supplier network development; strategic partnerships"],
        ["Brett Stokes",         "Chief Operating Officer",                 "Field operations; Gladstone Toll Mill commissioning; processing systems"],
        ["Dennis Eng",           "GTM Engineer & Capital Formation Arch.",  "KlickSmartAI founder; LeadOS & RIOS systems architect; investor acquisition"],
        ["Allan Fulsher",        "Securities Counsel",                       "Fulsher Law Group PC; Reg D 506(c) compliance; Colorado securities law"],
        ["Ocean Partners",       "Offtake Partner (Urban Mining)",          "Global precious metals trading and recycling firm; binding term sheet secured"]
      ],
      [2000, 2800, 4560]
    ),
    sp(120),

    sectionLabel("Next Steps — How to Proceed"),
    sp(80),
    body("Qualified accredited investors who wish to proceed should complete the following steps:"),
    sp(60),
    check("Step 1: Complete the Accreditor Investor Questionnaire (provided by Breakthrough Management)"),
    check("Step 2: Review and sign the Non-Disclosure Agreement via Avestor investor portal"),
    check("Step 3: Access the full Data Room (financial model, engineering reports, legal documents)"),
    check("Step 4: Schedule a 30-minute due diligence call with Andrew Ferguson or Dennis Eng"),
    check("Step 5: Review and execute Subscription Agreement (prepared by Fulsher Law Group PC)"),
    check("Step 6: Wire transfer or ACH via Avestor platform — minimum $25,000"),
    sp(80),

    body("Contact Information", { bold: true, color: NAVY }),
    kv("Andrew Ferguson — Breakthrough Management", "andrew@breakthroughmanagementllc.com"),
    kv("Dennis Eng — KlickSmartAI (Investor Acquisition)", "commercialfinance.deng@gmail.com"),
    kv("Securities Counsel", "Fulsher Law Group PC — Allan Fulsher"),
    kv("Investor Portal", "Avestor — link provided upon NDA execution"),
    sp(120),

    hr(GOLD),
    new Paragraph({
      children: [new TextRun({
        text: "This Memorandum is confidential and intended solely for accredited investors. Securities offered under Reg D 506(c). No representation is made that the Companies will achieve any projected financial result. All investments involve risk. KlickSmartAI provides marketing systems architecture only and does not provide legal, financial, or securities advice.",
        size: 16, color: MID_GRAY, italics: true, font: "Arial"
      })],
      alignment: AlignmentType.CENTER,
      spacing: { before: 120, after: 0 }
    })
  ];
}

// ═════════════════════════════════════════════════════════════════════════════
// ASSEMBLE DOCUMENT
// ═════════════════════════════════════════════════════════════════════════════

const doc = new Document({
  numbering: { config: numberingConfig },
  styles: {
    default: {
      document: { run: { font: "Arial", size: 22, color: SLATE } }
    },
    paragraphStyles: [
      {
        id: "Heading1", name: "Heading 1", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 32, bold: true, font: "Arial", color: NAVY },
        paragraph: { spacing: { before: 240, after: 160 }, outlineLevel: 0 }
      },
      {
        id: "Heading2", name: "Heading 2", basedOn: "Normal", next: "Normal", quickFormat: true,
        run: { size: 26, bold: true, font: "Arial", color: SLATE },
        paragraph: { spacing: { before: 160, after: 120 }, outlineLevel: 1 }
      }
    ]
  },
  sections: [
    {
      properties: {
        page: {
          size: { width: PAGE_W, height: PAGE_H },
          margin: { top: MARGIN, right: MARGIN, bottom: MARGIN, left: MARGIN }
        }
      },
      headers: { default: docHeader },
      footers: { default: docFooter },
      children: [
        ...buildCoverPage(),
        ...buildDisclaimerPage(),
        ...buildExecutiveSummary(),
        ...buildMarketOpportunity(),
        ...buildMineTeckSection(),
        ...buildUrbanMiningSection(),
        ...buildGTMStrategy(),
        ...buildUseOfFunds(),
        ...buildFinancials(),
        ...buildRiskFactors(),
        ...buildTeamPage()
      ]
    }
  ]
});

// ─── Write to file ────────────────────────────────────────────────────────────
Packer.toBuffer(doc).then(buffer => {
  const outputPath = "MineTeck_UrbanMining_Capital_Raise_Proposal.docx";
  fs.writeFileSync(outputPath, buffer);
  console.log(`\n✅ Document generated: ${outputPath}`);
  console.log(`   Size: ${(buffer.length / 1024).toFixed(1)} KB`);
  console.log(`\n   Open with Microsoft Word or LibreOffice.\n`);
}).catch(err => {
  console.error("❌ Error generating document:", err);
  process.exit(1);
});
